### PR TITLE
Serverspec to InSpec migration

### PR DESCRIPTION
**Pull request by chris-rock**
## Description

This PR migrates the existing integration tests to InSpec. It does this with minimal changes. Also it uses the same tests for `default` and `prefork` suite. 

### Check List
- [x] All tests pass. See https://github.com/chef-brigade/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

screen shot 2017-01-04 at 2 05 10 pm

### CODE REVIEW

**Comment by chris-rock** [comment]
Anything I can do to get this merged?

**Comment by svanzoest** [comment]
I need to test this on all platforms and verify it truly tests for
success.  I hopefully will get to that in the next week or so.

Can you confirm this does not break fixtures for chefspec? I have not had a
chance to check.

**Comment by chris-rock** [comment]
ChefSpec is executed in travis: https://travis-ci.org/sous-chefs/apache2/builds/188876022#L222 I fixed the location there as well.

**Comment by chris-rock** [comment]
@svanzoest Any updates on that?

**Comment by damacus** [comment]
The only difference (apart from the verifier) is the new error from the `default-debian-86 ` verifier. 

According to inspec apache2 *isn't* running. But:
```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─forking.conf
   Active: active (running) since Sat 2017-02-04 19:47:14 UTC; 1min 26s ago
  Process: 3728 ExecStart=/etc/init.d/apache2 start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/apache2.service
           ├─3744 /usr/sbin/apache2 -k start
           ├─3747 /usr/sbin/apache2 -k start
           ├─3749 /usr/sbin/apache2 -k start
           ├─3750 /usr/sbin/apache2 -k start
           └─3751 /usr/sbin/apache2 -k start

Feb 04 19:47:13 working.computers.biz systemd[1]: Starting LSB: Apache2 web server...
Feb 04 19:47:14 working.computers.biz apache2[3728]: Starting web server: apache2.
Feb 04 19:47:14 working.computers.biz systemd[1]: Started LSB: Apache2 web server.
```

**Comment by tas50** [comment]
We have a failure on Debian 8.6, but that's an Inspec issue and there's not much we can do to work around that at the moment. There's an issue for it upstream.

**Comment by chris-rock** [comment]
Related to https://github.com/chef/inspec/issues/931

**Pull request merged**
