### PR TITLE
Increase minimum chef version

### PR DESCRIPTION
**Pull request by bplessis**
# Description

Resource property 'documentation' field has been added at 13.9 release, version should be bumped to that number at minima

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by damacus** [comment]
I think we can just drag our heels for a couple of weeks on this and just bump it straight to 14.0

**Comment by bplessis** [comment]
Shouldn't the question be "is there a useful and required feature of 14.x that we will use" ? :)

**Comment by MarkGibbons** [comment]
This version doesn't work on 13, so I'm in favor of bumping the minimum version to 14.0.  The description settings on the resource properties didn't compile on 13.8.5.

**Comment by damacus** [comment]
Not really :) 
We support "current Chef -1"

**Pull request merged**
