### PR TITLE
mod info arguments type consistency with mod-status

### PR DESCRIPTION
**Pull request by bplessis**
# Description

Allow passing the list of allowed networks for mod_info using an Array like mod-status

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
To keep my design argument consistent from the other PR, I think we should allow Arrays here instead of both String and Arrays. So the direction you're taking makes this WAY clearer :) 
This is probably a breaking change though (if switching from String to Array), so a minor version bump.

**Comment by bplessis** [comment]
> This is probably a breaking change though (if switching from String to Array), so a minor version bump.

The way i did it it's backward compatible, the conversion from String to Array is done silently, so there is not breaking change (in my patch) but one could be planned for a futur release that will remove the String version altogether.

For mod_status however i could remove the string way since it didn't exist previously

**Comment by damacus** [comment]
I'm going to merge this in. I'm pretty sure this shouldn't be breaking, so I'm really happy with this change. 

Thanks very much!

**Pull request merged**
