### PR TITLE
Enhance install resource to avoid configuration rewriting

### PR DESCRIPTION
**Pull request by bplessis**
# Description

With the new (from my 3.1 perspective) ressource orientation setting the mpm configuration, removing a 'default' module or changing configuration from a default mobule induce un-necessary configuration flapping.

This PR add three properties to the install ressource to help prevent that:

 * mpm_conf: like mod_conf of module ressource, help passing parameters to the selected mpm (should be used with `mpm` property).
 * modules: allow to alter list of default modules installed.
 * mod_conf: Hash of mod_conf Hash to set defaults modules parameters.

The mod_conf property can also be used to specify mpm parameters if you would like to keep the per-platform default mpm

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
How are you seeing the resource flapping? It should be just setting it and it's always like that.

**Comment by bplessis** [comment]
You can see it while the run is in progress, when processing the apache2_install resource the mpm and modules configuration will be updated (and backup-ed in /var/chef/backups), files dates will be changed, etc) to the default settings, and then when processing an "apache2_module" directive, or "apache2_mpm_*" directives configuration will be changed again.

**Comment by damacus** [comment]
Sorry for taking so long to get back to you on this one.

Can you :
- Add a test for a single platform with a different mpm to help avoid further regressions. If you can figure out a way to say that the mpm resource should only be in the resource collection once or something that'd be great 
- Add a changelog
-Fix the delivery warnings

**Comment by damacus** [comment]
Oops did you want this going into the 7.0 release notes, or 7.1?

**Comment by damacus** [comment]
Awesome work by the way, thanks for adding documentation.

**Comment by bplessis** [comment]
Le 27 avril 2019 10:33:06 Dan Webb <notifications@github.com> a écrit :
> Oops did you want this going into the 7.0 release notes, or 7.1?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
Hum sorry didn't think about it, I just filled in the latest entry, I was 
under the impression that 7.0 wasn't "released" as of now.


I will investigate the testing framework and see if I can find a good test 
to be done

**Comment by damacus** [comment]
Yeah it's been tagged in git and is on supermarket as of a few weeks ago.

No rush with the tests if you need help feel free to jump on the sous chefs channel on the chef community slack

**Comment by damacus** [comment]
Nice one! :)

**Comment by bplessis** [comment]
Thanks,
Actually i'm wondering if it would be possible and better to do it another way:

 have all ressources (apache2_install / apache2_modules / ..) only build an in-memory (using node.run_state) status of the configuration, and trigger the file creation at the very end of the run (using a recipe with ruby_block for example)

That way even conflicting over-riding of modules configuration due to multiple meta-cookbook won't cause the issue at hand...

**Pull request merged**
