### PR TITLE
Avoid name collisions: Disable including helpers module in Recipe/Resource class

### PR DESCRIPTION
**Pull request by bottkv488**
# Description
i.e. docker fails because of `libexec_dir` name collision in `librarie/helpers.rb`.
* fixed include
* fixed nested array
* added test stub

## Issues Resolved

[List any existing issues this PR resolves]

## Check List

- [x ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md

### CODE REVIEW

**Comment by damacus** [comment]
Hey thanks for this, I don't think this is the correct approach to fixing this. 

I'll get some time shortly to release without these at all.

**Comment by bottkv488** [comment]
@damacus sorry to hear that, because it's a real blocker for us:
After all it is a released cookbook, and it breaks docker as soon as it's in the runlist ...

**Comment by damacus** [comment]
I'll have this fixed in the next week or so. It'll be a major release. But I'm pretty happy it should be fixed.

**Comment by damacus** [comment]
Fixed by #611

**Comment by bottkv488** [comment]
NP, just wanted to help ;)

I guess you still might want to fix
https://github.com/sous-chefs/apache2/blob/6f3502150f3cc6c5facb427d9c024280e1909239/libraries/helpers.rb#L269
?
(That's why I added the new spec test, because the current one didn't catch the nested array)

**Comment by damacus** [comment]
Really appreciate the help here. It's honestly amazing.

I thought this should have been covered by the current default_modules_spec.rb no? 🤔 (generally don't know the answer to this one!)

**Comment by bottkv488** [comment]
I did not dig any further, my first guess would be that the log resource flattens the array?

**Pull request closed without merging**
