### PR TITLE
Add variables property to default_site resource

### LINKED ISSUE #744: The default_site resource does not support custom variables
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

The `default_site` resource does not support passing custom variables into a user-provided template. It would be excellent if the `default_site` resource allowed for arbitrary custom variables to be passed in.

## :grey_question: Possible Solution

Add a `variables` property to the `default_site` resource, that is passed into the internal template resource.

## :arrow_heading_up: Describe alternatives you've considered

The `conf` resource provides the `options` property, which does the same thing. This can be (ab)used by passing in a path to the _sites-available_ directory. However, that blurs the lines of what result the resources are intended to achieve. A second alternative is to simply render the site template directly, but calls into question why one would use this cookbook in the first place.

## :heavy_plus_sign: Additional context

Tested with `apache2` v8.11.1

### PR DESCRIPTION
**Pull request by freakinhippie**
# Description

Added the ability to pass custom variables into the `default_site`
resource by exposing a `variables` property.

Also refactored the ssl-* test suite to use the new functionality
as well as use chef's built-in certificate generation resources
instead of execute calls to openssl.

Fixed bug in handling of `site_action` property of `default_site`
resource which ignored any non-default setting.

## Issues Resolved

#744 
#745 

## Check List

- [X] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
FYI: The ChefSpec errors are due to this: https://github.com/berkshelf/berkshelf/pull/1866

**Comment by freakinhippie** [comment]
Thank you @ramereth, please let me know if I need to do anything further.

**Comment by ramereth** [comment]
@freakinhippie unfortunately we're going to need to wait until this fix gets through a new release of Chef Workstation

**Comment by freakinhippie** [comment]
Hi @ramereth, I see that chef-workstation was released and you restarted the checks. The failure on `default-centos-8` is not introduced by this change. However, would you like me to look at implementing a fix?

**Comment by ramereth** [comment]
> Hi @ramereth, I see that chef-workstation was released and you restarted the checks. The failure on `default-centos-8` is not introduced by this change. However, would you like me to look at implementing a fix?

I'm going to make a separate PR which fixes it. Thanks!

**Comment by ramereth** [comment]
@freakinhippie can you please rebase this?

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.12.0](https://github.com/sous-chefs/apache2/releases/tag/8.12.0)

**Pull request merged**
