### PR TITLE
undefined method `apache_root_group' for Chef::Resource::Template in resource/default_site.rb

### PR DESCRIPTION
**Pull request by bplessis**
I'm not sure why the need to use a "template" ressource to in fact delete a file, but in the current version the :disable action fail with :

  undefined method `apache_root_group' for Chef::Resource::Template

so added the necessary "new_resource." prefix

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Weird I'm not sure how the testing didn't pick this up. 

What caused it to occur before you fixed it?

**Comment by damacus** [comment]
it made sense at the time to use the template resource to delete the file that was created by the template resource.

**Comment by bplessis** [comment]
> Weird I'm not sure how the testing didn't pick this up.
> 
> What caused it to occur before you fixed it?

just adding the code from `test/cookbooks/test/recipes/basic_site.rb`
```ruby
apache2_site '000-default' do
  action :disable
end
```
triggered the error (with latest chef 14.x)

**Pull request merged**
