### PR TITLE
Add envvars_additional_params property to install resource

### PR DESCRIPTION
**Pull request by hrak**
This allows custom environment variables to be added to the envvars file

Signed-off-by: Hans Rakers <hans@shoq.com>

# Description

This PR revives work submitted earlier in #451 that never got merged. This change allows custom environment variables to be added to the envvars file (For example: override file descriptor limit, set ORACLE_HOME, etc.)

I didn't add tests since `sysconfig_additional_params` has no tests either.

## Issues Resolved

#451 

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ramereth** [comment]
@hrak can you please add some unit and integration tests?

**Comment by hrak** [comment]
@ramereth tests have been added

**Comment by hrak** [comment]
Ok this should be good now, `sysconfig_additional_params` is tested now too as an extra :)

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.14.0](https://github.com/sous-chefs/apache2/releases/tag/8.14.0)

**Pull request merged**
