### PR TITLE
default_apache_root_group: defer to ohai

### PR DESCRIPTION
**Pull request by josephholsten**
defer implementation of root group selection to https://github.com/jugatsu/ohai/blob/master/lib/ohai/plugins/root_group.rb

### CODE REVIEW

**Comment by damacus** [comment]
Chsnglog please :smile:

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
This looks like it's broken a bunch of Unit tests. @josephholsten can you look at fixing those please?

**Comment by JohnRoesler** [comment]
delivery tests are failing @josephholsten

**Comment by damacus** [comment]
Closing this as the tests need reworking to reflect the new method of getting the root group. If someone fancies kicking this up please be my guest!

**Comment by josephholsten** [comment]
@damacus @JohnRoesler do we trust fauxhai to stub this stuff? I honestly would prefer to remove the tests entirely because this stuff should be tested in ohai.

**Comment by damacus** [comment]
Yep, happy if that's the fix (defer to ohai) but we just either need to fix/remove these tests not just have this PR sitting around for months half finished :(

**Pull request closed without merging**
