### PR TITLE
resource/install.rb: Auto-convert the listen property to an Array when it's a type String

### PR DESCRIPTION
**Pull request by bplessis**
# Description

Install resource specify the listen property as a String or an Array, however <% @listen.each do |value| -%> will fail when listen is of type String, so do a inconditionnal upgrade to an Array before handling the value to the template.

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
I think in this case we should just allow Arrays as it's a plural "ports" so the use should really expect an Array in this case.

**Comment by bplessis** [comment]
Hi, didn't saw your previous message, i can redo the PR to remove the String option in this case

**Comment by damacus** [comment]
Nah we should be good for now, I think(!)

We can simplify on just an Array at a later date.

**Pull request merged**
