### PR TITLE
mod-ssl resource and testing

### LINKED ISSUE #570: Resource: apache2_website
### Cookbook version
- 6.0.0-beta

### Chef-client version
- Latest

### Platform Details
- All supported platforms

### Scenario:
As a user
I want to be able to create and enable a website
So that I can create websites using the apache2 cookbook

As a user
I want to be able to create website content that users cannot see
So that I can stage changes 

### Acceptance Criteria
- [x] apache2_website resource that creates a website
- [ ] apache2_website resource that creates a website in a disabled state. 
- [x] Unit tests for templates and resource
- [x] Inspec tests
- [x] New kitchen suite for this resource.

### LINKED ISSUE #577: Resource: update mod_ssl
### Cookbook version
6.0.0-beta

### Chef-client version
Latest

### Platform Details
- All supported

### Scenario:
As a user
I want to be able to configure mod_ssl via properties rather than attributes
So that I can interact with mods in the same way.

### Expected Result:
- [ ] apache2_mod_ssl is configurable via resource properties
- [ ] mod_ssl has unit tests 
- [ ] no attributes under node['apache']['mod_ssl'] exist

### PR DESCRIPTION
**Pull request by damacus**
## Description

- Adds basic site example
- Adds SSL site example

### Issues Resolved

Fixes #570 
Fixes #577 

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This is a big Pull Request.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
CHANGELOG coming later when I've decided what I'm changing... 

This currently doesn't seem to pass spec tests due to it not finding the execute resource in the collection. I'm not sure why this doesn't work compared to what mod_auth_cas does (which from my tired eyes looks the same)

**Comment by JohnRoesler** [comment]
On notifies, Rob shared a work around in slack as chefspec has a bug that's causing the failure.

> When it came up for me, I inverted the notifies to a subscribes. Put a subscribes on that execute resource and reference the resource that currently has the notifies.

**Comment by damacus** [comment]
Update: SSL, Basic site are all working on CentOS-7

Debian/Ubuntu now needs extra work. 
Looks like the default site config has broken again. Time to play more wackamole

**Pull request merged**
