### PR TITLE
Add missing unified_mode from mod_php and mod_wscgi

### PR DESCRIPTION
**Pull request by damacus**
# Description

- Add missing unified_mode from mod_php and mod_wscgi
- Fix service resource restarting the apache service every run

## Issues Resolved

Chef 17 errors with the apache2 cookbook

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by bmhughes — DISMISSED** [review]

**Review by ramereth — CHANGES_REQUESTED** [review]
`chef_version` should be updated to be `>= 15.3` in `metadata.rb` as that is the first release that 15 supported unified mode.

**Comment by damacus** [comment]
I was actually going to go for >= 16, seeing at 17 is out now.

**Comment by tas50** [comment]
15.3+ please

**Comment by ramereth** [comment]
Please keep 15.3+ support

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [8.11.0](https://github.com/sous-chefs/apache2/releases/tag/8.11.0)

**Pull request merged**
