### PR TITLE
Add CentOS 8 to CI pipeline

### PR DESCRIPTION
**Pull request by ramereth**
# Description

[Describe what this change achieves]

## Issues Resolved

[List any existing issues this PR resolves]

## Check List

- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by Xorima** [comment]
Hey @ramereth 

Could you take a look at the test failures, looks like the tests may need tweaking slightly for the wording in centos 8?

**Comment by ramereth** [comment]
@Xorima yes, I was planning on looking into them and fixing them just haven't gotten around to them yet!

**Comment by damacus** [comment]
FWIW: This looks like a similar problem to CentOS-7 and it's default site.

**Comment by ramereth** [comment]
> FWIW: This looks like a similar problem to CentOS-7 and it's default site.

Yes, I noticed that as well. I was planning on fixing that on this PR as well. I should get to this next week hopefully.

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
